[workspace]

members = [
  "wuzei",
  "huazhi",
]

[workspace.dependencies]
huazhi = { path = "./huazhi" }

hraw = { git = "https://github.com/haitusense/hraw/", features=[] }
# hraw = { path = "../hraw" }

anyhow = "1.0.81"
thiserror = "1.0.58"

serde_json = "1.0.114"