[package]
name = "wuzei"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
huazhi = { workspace = true }

anyhow = "*"
thiserror = "*"
colored = "*"
indoc = "*"
include_dir = "0.7.3"
clap = { version = "4.5.1", features = ["derive",] }
tokio = { version = "1.36.0", features = ["full"] }

hraw = { git = "https://github.com/haitusense/hraw/" }

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

image = "0.24.9"      # use icon

[target.'cfg(windows)'.build-dependencies]  
windres = "0.2.2"     # use icon
